### ISSUE TITLE
Core - Core refactor

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger/iota.c#306]
## Description

For clean up and better code structures
- remove `transaction_payload_type_t`, add essence enum when protocol support different types
- remove transaction wrapper methods in `core/payloads/transaction.c`
  - tx_payload_add_input
  - tx_payload_add_output
  - tx_payload_add_sig_block
  - tx_payload_add_ref_block

**Comment by matjazv** [comment]
- reorganize files inside `client/api/json_parser` in a way they are in `core/models`
- remove `#define`s like `*_HEX_BYTES` and replace usages of those `#define`s with `BIN_TO_HEX_BYTES` macro
- consider using just one type of array in a code (uthash, utarray and utlist)
- double check all `#define`s
  - can some `#define` be removed because it's a redundant
  - can some `#define` be moved somewhere else
  - should we have a separate `.h` file for a common `#define`s
- unify names for `message` payload: `transaction_payload_t` vs `tagged_data_t` vs `milestone_t`
- is it necessary that `payload_len` is in `transaction_essence_t` structure? It can be calculated.

**Comment by oopsmonk** [comment]
> unify names for message payload: transaction_payload_t vs tagged_data_t vs milestone_t

rename structures with the name defined in TIPs. for instance `transaction_payload_t`, `tagged_data_payload_t`, `milestone_payload_t`....

> is it necessary that payload_len is in transaction_essence_t structure? It can be calculated.

remove the `payload_len` from transaction_essence_t

**Comment by oopsmonk** [comment]
> * reorganize files inside client/api/json_parser in a way they are in core/models
> * consider using just one type of array in a code (uthash, utarray and utlist)

move to client refactor #346
